[package]
name = "modbus_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#modbus-core = { version = "0.1.0", default-features = false, features = ["rtu"] }
